webtalk_init -webtalk_dir C:/Users/Administrator/Desktop/joystick_lz_final/joystick_lz.sim/sim_1/behav/xsim.dir/test_bentch_control_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Feb 09 23:12:06 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2014.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1071353" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174679548_176449548_210592822_043" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5069ae61-7eee-418c-bb88-d3f00b817c0b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "aada24dcd3844316af7ff887dc03342e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3591 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.36_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "30128_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1652960733 -regid "174679548_176449548_210592822_043" -xml C:/Users/Administrator/Desktop/joystick_lz_final/joystick_lz.sim/sim_1/behav/xsim.dir/test_bentch_control_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Administrator/Desktop/joystick_lz_final/joystick_lz.sim/sim_1/behav/xsim.dir/test_bentch_control_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Administrator/Desktop/joystick_lz_final/joystick_lz.sim/sim_1/behav/xsim.dir/test_bentch_control_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
