# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -id {Vivado 12-172}  -suppress 
set_msg_config  -id {Wavedata 42-52}  -suppress 

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.cache/wt [current_project]
set_property parent.project_path C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files C:/Users/nfxz/Desktop/Project/FPGA/Doc/tank_rom/tank_prom.coe
add_files C:/Users/nfxz/Desktop/Project/FPGA/Doc/tank_rom/tank_vrom.coe
add_files C:/Users/nfxz/Desktop/Project/FPGA/Doc/tank_rom/tank_OAM.coe
add_files C:/Users/nfxz/Desktop/Project/FPGA/Doc/tank_rom/tank_vram.coe
add_files C:/Users/nfxz/Desktop/Project/FPGA/Doc/tank_rom/tank_Palette.coe
add_files C:/Users/nfxz/Desktop/Project/FPGA/Doc/tank_rom/color_table.coe
add_files C:/Users/nfxz/Desktop/Project/Doc/tank_rom/tank_prom.coe
add_files C:/Users/nfxz/Desktop/Project/Doc/tank_rom/tank_vrom.coe
add_files C:/Users/nfxz/Desktop/Project/Doc/tank_rom/tank_OAM.coe
add_files C:/Users/nfxz/Desktop/Project/Doc/tank_rom/tank_vram.coe
add_files C:/Users/nfxz/Desktop/Project/Doc/tank_rom/tank_Palette.coe
add_files C:/Users/nfxz/Desktop/Project/Doc/tank_rom/color_table.coe
add_files C:/Users/nfxz/Desktop/Project/FPGA/Doc/img/Palette.coe
add_files C:/Users/nfxz/Desktop/Project/FPGA/Doc/img/VRAM.coe
add_files C:/Users/nfxz/Desktop/Project/FPGA/Doc/img/OAM.coe
add_files C:/Users/nfxz/Desktop/Project/FPGA/Doc/img/VROM.coe
add_files C:/Users/nfxz/Desktop/Project/FPGA/Doc/tank_rom/tank_prom_test.coe
add_files C:/Users/nfxz/Desktop/Project/FPGA/Doc/tank_rom/tank_prom_mid.coe
add_files C:/Users/nfxz/Desktop/Project/FPGA/Doc/tank_rom/tank_pram.coe
add_files -quiet C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.runs/PROM_synth_1/PROM.dcp
set_property used_in_implementation false [get_files C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.runs/PROM_synth_1/PROM.dcp]
add_files -quiet C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.runs/PRAM_synth_1/PRAM.dcp
set_property used_in_implementation false [get_files C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.runs/PRAM_synth_1/PRAM.dcp]
add_files -quiet C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.runs/VROM_synth_1/VROM.dcp
set_property used_in_implementation false [get_files C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.runs/VROM_synth_1/VROM.dcp]
add_files -quiet C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.runs/OAM_synth_1/OAM.dcp
set_property used_in_implementation false [get_files C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.runs/OAM_synth_1/OAM.dcp]
add_files -quiet C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.runs/Palette_synth_1/Palette.dcp
set_property used_in_implementation false [get_files C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.runs/Palette_synth_1/Palette.dcp]
add_files -quiet C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.runs/COLOR_TABLE_synth_1/COLOR_TABLE.dcp
set_property used_in_implementation false [get_files C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.runs/COLOR_TABLE_synth_1/COLOR_TABLE.dcp]
add_files -quiet C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.runs/VRAM_synth_1/VRAM.dcp
set_property used_in_implementation false [get_files C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.runs/VRAM_synth_1/VRAM.dcp]
read_verilog -library xil_defaultlib -sv {
  C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/imports/new/joy_counter.sv
  C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/new/PPU_PALETTE_FSM.sv
  C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/new/PPU_SP_FSM.sv
  C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/new/PPU_MAIN_LOOP.sv
  C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/new/PPU_BG_FSM.sv
  C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/new/DMA.sv
  C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/new/main_loop.sv
  C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/imports/new/digit2seg.sv
  C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/imports/new/decoder3_8.sv
  C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/imports/new/createHV.sv
  C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/imports/new/joy_data.sv
  C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/imports/new/control.sv
  C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/imports/new/joystick.sv
  C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/new/PPU.sv
  C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/imports/new/vga.sv
  C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/imports/new/seg.sv
  C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/new/CPU.sv
  C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/new/button_input.sv
  C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/imports/new/CPU_PPU_CHIP_TEST.sv
}
read_xdc C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/constrs_1/imports/Doc/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/constrs_1/imports/Doc/Nexys4_Master.xdc]

catch { write_hwdef -file CPU_PPU_CHIP_TEST.hwdef }
synth_design -top CPU_PPU_CHIP_TEST -part xc7a100tcsg324-1
write_checkpoint -noxdef CPU_PPU_CHIP_TEST.dcp
catch { report_utilization -file CPU_PPU_CHIP_TEST_utilization_synth.rpt -pb CPU_PPU_CHIP_TEST_utilization_synth.pb }
