# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/ip/PRAM/PRAM.xci
# IP: The module: 'PRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/ip/PRAM/PRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/ip/PRAM/PRAM.xci
# IP: The module: 'PRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nfxz/Desktop/Project/FPGA/nes/nes.srcs/sources_1/ip/PRAM/PRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
