# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-3
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/joystick_lz_final/joystick_lz.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/joystick_lz_final/joystick_lz.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/Administrator/Desktop/joystick_lz_final/joystick_lz.srcs/sources_1/new/joy_counter.sv
  C:/Users/Administrator/Desktop/joystick_lz_final/joystick_lz.srcs/sources_1/new/control.sv
  C:/Users/Administrator/Desktop/joystick_lz_final/joystick_lz.srcs/sources_1/imports/new/joystick.sv
  C:/Users/Administrator/Desktop/joystick_lz_final/joystick_lz.srcs/sources_1/new/test_cnt.sv
  C:/Users/Administrator/Desktop/joystick_lz_final/joystick_lz.srcs/sources_1/new/test_bentch_control.sv
  C:/Users/Administrator/Desktop/joystick_lz_final/joystick_lz.srcs/sources_1/new/joy_data.sv
}
read_xdc C:/Users/Administrator/Desktop/joystick_lz_final/joystick_lz.srcs/constrs_1/imports/Document/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Administrator/Desktop/joystick_lz_final/joystick_lz.srcs/constrs_1/imports/Document/Nexys4_Master.xdc]

catch { write_hwdef -file joystick.hwdef }
synth_design -top joystick -part xc7a100tcsg324-3
write_checkpoint -noxdef joystick.dcp
catch { report_utilization -file joystick_utilization_synth.rpt -pb joystick_utilization_synth.pb }
